---
- name: Open TCP firewall ports for Plex
  firewalld:
    port: "{{ item }}"
    zone: public
    permanent: yes
    state: enabled
  loop: "{{ plex_firewall_tcp_ports }}"
  notify: reload firewalld

- name: Open UDP firewall ports for Plex
  firewalld:
    port: "{{ item }}"
    zone: public
    permanent: yes
    state: enabled
  loop: "{{ plex_firewall_udp_ports }}"
  notify: reload firewalld
